In [71]:
from fancyimpute import SimpleFill, KNN, IterativeImputer, IterativeSVD
import numpy as np
import pandas as pd
from sklearn import preprocessing

In [72]:
pwd()

'/Users/daisyding/Dropbox/StarterCode'

In [73]:
missing = np.load("./Data/uci/len6336rate0.7seed0.npy")

In [74]:
missing

array([ True, False,  True, ...,  True, False,  True])

In [75]:
def process(df):
    df = df.drop(df.columns[[0, 1, 2]], axis=1)
    nrow, ncol = df.shape
    for i in range(nrow):
        for j in range(ncol):
            if df.iloc[i,j] == "?":
                df.iloc[i, j] = 0
                
    x = df.values
    min_max_scaler = preprocessing.MinMaxScaler()
    x_scaled = min_max_scaler.fit_transform(x)
    df_normalized = pd.DataFrame(x_scaled)
    return df_normalized

In [76]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wpbc.data',
                header=None)

In [77]:
df

0  1    2      3      4       5       6        7        8        9   \
0    119513  N   31  18.02  27.60  117.50  1013.0  0.09489  0.10360  0.10860   
1      8423  N   61  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.30010   
2    842517  N  116  21.37  17.44  137.50  1373.0  0.08836  0.11890  0.12550   
3    843483  N  123  11.42  20.38   77.58   386.1  0.14250  0.28390  0.24140   
4    843584  R   27  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.19800   
..      ... ..  ...    ...    ...     ...     ...      ...      ...      ...   
193  942640  N   10  22.52  21.92  146.90  1597.0  0.07592  0.09162  0.06862   
194  943471  N    8  15.44  31.18  101.00   740.4  0.09399  0.10620  0.13750   
195   94547  N   12  17.17  29.19  110.00   915.3  0.08952  0.06655  0.06583   
196  947204  R    3  21.42  22.84  145.00  1440.0  0.10700  0.19390  0.23800   
197  947489  N    6  16.70  28.13  110.30   885.4  0.08896  0.11310  0.10120   

     ...      25      26       27      28      29       30      31       32  \
0    ...  139.70  1436.0  0.11950  0.1926  0.3140  0.11700  0.2677  0.08113   
1    ...  184.60  2019.0  0.16220  0.6656  0.7119  0.26540  0.4601  0.11890   
2    ...  159.10  1949.0  0.11880  0.3449  0.3414  0.20320  0.4334  0.09067   
3    ...   98.87   567.7  0.20980  0.8663  0.6869  0.25750  0.6638  0.17300   
4    ...  152.20  1575.0  0.13740  0.2050  0.4000  0.16250  0.2364  0.07678   
..   ...     ...     ...      ...     ...     ...      ...     ...      ...   
193  ...  162.10  1902.0  0.08191  0.1319  0.1056  0.09378  0.2061  0.05788   
194  ...  112.60   929.0  0.12720  0.2362  0.2975  0.12860  0.2914  0.08024   
195  ...  132.50  1295.0  0.12610  0.1572  0.2141  0.09520  0.3362  0.06033   
196  ...  198.30  2375.0  0.14980  0.4379  0.5411  0.22150  0.2832  0.08981   
197  ...  128.80  1213.0  0.13300  0.2808  0.3455  0.13170  0.3035  0.08036   

      33  34  
0    5.0   5  
1    3.0   2  
2    2.5   0  
3    2.0   0  
4    3.5   0  
..   ...  ..  
193  6.0   2  
194  1.5   0  
195  3.7   0  
196  3.0   ?  
197  3.5   0  

[198 rows x 35 columns]

In [78]:
df = process(df)

In [79]:
df

0         1         2         3         4         5         6   \
0    0.434542  0.595848  0.413793  0.344948  0.285673  0.216883  0.210069   
1    0.432698  0.000000  0.461887  0.338594  0.622831  0.872621  0.685467   
2    0.640443  0.244291  0.595281  0.535586  0.192026  0.274543  0.252023   
3    0.028888  0.346021  0.051543  0.012974  0.968450  0.896363  0.539745   
4    0.574063  0.137024  0.573503  0.495340  0.363258  0.326927  0.432004   
..        ...       ...       ...       ...       ...       ...       ...   
193  0.711125  0.399308  0.680581  0.654205  0.013624  0.171735  0.110819   
194  0.275968  0.719723  0.264065  0.200593  0.272766  0.226682  0.281813   
195  0.382299  0.650865  0.345735  0.293211  0.208662  0.077256  0.103893   
196  0.643516  0.431142  0.663339  0.571065  0.459343  0.557189  0.531304   
197  0.353411  0.614187  0.348457  0.277378  0.200631  0.252685  0.191699   

           7         8         9   ...        22        23        24  \
0    0.277738  0.321594  0.277177  ...  0.371176  0.273322  0.267183   
1    0.700923  0.641455  0.603094  ...  0.676411  0.445050  0.570687   
2    0.339930  0.591801  0.208731  ...  0.503059  0.424431  0.262208   
3    0.469291  0.744226  1.000000  ...  0.093610  0.017556  0.909020   
4    0.464315  0.289261  0.181818  ...  0.456152  0.314266  0.394413   
..        ...       ...       ...  ...       ...       ...       ...   
193  0.239704  0.242494  0.050223  ...  0.523453  0.410586  0.000000   
194  0.247056  0.246536  0.228862  ...  0.186948  0.123980  0.321913   
195  0.167892  0.280023  0.077771  ...  0.322230  0.231789  0.314095   
196  0.616341  0.332564  0.306633  ...  0.769545  0.549913  0.482550   
197  0.163525  0.336028  0.214028  ...  0.297077  0.207635  0.363139   

           25        26        27        28        29        30        31  
0    0.140351  0.253067  0.336803  0.219200  0.171127  0.479167  0.185185  
1    0.610208  0.600269  0.904711  0.598462  0.418864  0.270833  0.074074  
2    0.291639  0.276976  0.666679  0.545831  0.233701  0.218750  0.000000  
3    0.809574  0.578454  0.874479  1.000000  0.773711  0.166667  0.000000  
4    0.152669  0.328109  0.510926  0.157500  0.142595  0.322917  0.000000  
..        ...       ...       ...       ...       ...       ...       ...  
193  0.080054  0.071220  0.247943  0.097773  0.018628  0.583333  0.074074  
194  0.183661  0.238669  0.381195  0.265918  0.165289  0.114583  0.000000  
195  0.105186  0.165896  0.253377  0.354228  0.034698  0.343750  0.000000  
196  0.384021  0.451231  0.736711  0.249754  0.228060  0.270833  0.000000  
197  0.227965  0.280554  0.393058  0.289769  0.166076  0.322917  0.000000  

[198 rows x 32 columns]

In [80]:
def construct_missing_X(missing_list, df):
    nrow, ncol = df.shape
    data_incomplete = np.zeros((nrow, ncol))
    data_complete = np.zeros((nrow, ncol))
    missing_ind = missing_list.reshape(nrow, ncol)
    for i in range(nrow):
        for j in range(ncol):
            data_complete[i,j] = df.iloc[i,j]
            if missing_ind[i,j]:
                data_incomplete[i,j] = df.iloc[i,j]
            else:
                data_incomplete[i,j] = np.NaN
    return data_complete, data_incomplete

In [81]:
X, X_incomplete = construct_missing_X(missing, df)
X_incomplete

array([[0.4345421 ,        nan, 0.4137931 , ..., 0.17112685, 0.47916667,
               nan],
       [0.43269822, 0.        , 0.46188748, ..., 0.41886396, 0.27083333,
        0.07407407],
       [0.64044253, 0.24429066,        nan, ...,        nan, 0.21875   ,
        0.        ],
       ...,
       [       nan, 0.65086505, 0.34573503, ...,        nan,        nan,
               nan],
       [0.64351567,        nan, 0.66333938, ..., 0.22805982, 0.27083333,
               nan],
       [0.35341119,        nan, 0.34845735, ..., 0.16607635,        nan,
        0.        ]])

In [82]:
X_filled_knn = KNN(k=3).fit_transform(X_incomplete)

Imputing row 1/198 with 13 missing, elapsed time: 0.029
Imputing row 101/198 with 6 missing, elapsed time: 0.047


In [83]:
X_filled_knn

array([[0.4345421 , 0.31828355, 0.4137931 , ..., 0.17112685, 0.47916667,
        0.        ],
       [0.43269822, 0.        , 0.46188748, ..., 0.41886396, 0.27083333,
        0.07407407],
       [0.64044253, 0.24429066, 0.54600751, ..., 0.15862642, 0.21875   ,
        0.        ],
       ...,
       [0.39049908, 0.65086505, 0.34573503, ..., 0.07909817, 0.37273378,
        0.12604804],
       [0.64351567, 0.35645555, 0.66333938, ..., 0.22805982, 0.27083333,
        0.02829843],
       [0.35341119, 0.38586818, 0.34845735, ..., 0.16607635, 0.30041061,
        0.        ]])

In [84]:
diff = X - X_filled_knn
diff

array([[ 0.        ,  0.2775642 ,  0.        , ...,  0.        ,
         0.        ,  0.18518519],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.0492738 , ...,  0.07507422,
         0.        ,  0.        ],
       ...,
       [-0.00820037,  0.        ,  0.        , ..., -0.04440055,
        -0.02898378, -0.12604804],
       [ 0.        ,  0.07468632,  0.        , ...,  0.        ,
         0.        , -0.02829843],
       [ 0.        ,  0.22831867,  0.        , ...,  0.        ,
         0.02250606,  0.        ]])

In [86]:
missing

array([ True, False,  True, ...,  True, False,  True])

In [90]:
n_missing = len(missing) - sum(missing)

In [91]:
MAE = sum(sum(abs(diff))) / n_missing

In [92]:
MAE

0.08768465393524684

In [93]:
X_filled_mean = SimpleFill().fit_transform(X_incomplete)

In [94]:
sum(sum(abs(X_filled_mean - X))) / n_missing

0.13044041684456995

In [95]:
X_filled_mice = IterativeImputer().fit_transform(X_incomplete)
sum(sum(abs(X_filled_mice - X))) / n_missing

/miniconda3/envs/graph/lib/python3.7/site-packages/sklearn/impute/_iterative.py:603: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  " reached.", ConvergenceWarning)


0.055874663004220185

In [96]:
X_filled_svd = IterativeSVD().fit_transform(X_incomplete)
sum(sum(abs(X_filled_svd - X))) / n_missing

[IterativeSVD] Iter 1: observed MAE=0.128283
[IterativeSVD] Iter 2: observed MAE=0.085944
[IterativeSVD] Iter 3: observed MAE=0.061847
[IterativeSVD] Iter 4: observed MAE=0.042004
[IterativeSVD] Iter 5: observed MAE=0.031415
[IterativeSVD] Iter 6: observed MAE=0.029509
[IterativeSVD] Iter 7: observed MAE=0.028677
[IterativeSVD] Iter 8: observed MAE=0.028237
[IterativeSVD] Iter 9: observed MAE=0.027958
[IterativeSVD] Iter 10: observed MAE=0.027772
[IterativeSVD] Iter 11: observed MAE=0.027626
[IterativeSVD] Iter 12: observed MAE=0.027510
[IterativeSVD] Iter 13: observed MAE=0.027413
[IterativeSVD] Iter 14: observed MAE=0.027325
[IterativeSVD] Iter 15: observed MAE=0.027243
[IterativeSVD] Iter 16: observed MAE=0.027172
[IterativeSVD] Iter 17: observed MAE=0.027107
[IterativeSVD] Iter 18: observed MAE=0.027044
[IterativeSVD] Iter 19: observed MAE=0.026985
[IterativeSVD] Iter 20: observed MAE=0.026929
[IterativeSVD] Iter 21: observed MAE=0.026875
[IterativeSVD] Iter 22: observed MAE=0.0268

0.07604318196034113